### ISSUE TITLE
UrlSessionTracking not working

### ISSUE THREAD

**Issue by foch** [AmadeusITGroup/HttpSessionReplacer#10]
Hello
I'm afraid the UrlSessionTracking is not properly working, for 2 reasons:

1/ Simple one, the URL token must be JSESSIONID, and the only way to change it is to set the context param SESSION_ID_NAME  = "com.amadeus.session.cookieName", which makes no sense. Indeed the constant SESSION_ID_NAME is used for both cases, URL and Cookie.
The name should be different for URL and Cookie, or a generic name could be given, such "as com.amadeus.session.sessionName"

2/ More importantly, it doesn't work properly because of what I think is a design issue.
Indeed, in JBoss, when we call request.getPathInfo(); the jsessionid is removed (I guess by JBoss).
I had the problem in my complex webapp, and in order to be sure that it wasn't due to my webapp, I created a reproducer webapp [ServletSessionURLRewriting.zip](https://github.com/AmadeusITGroup/HttpSessionReplacer/files/913757/ServletSessionURLRewriting.zip)
 (shamelessly copied from http://www.journaldev.com/1907/java-session-management-servlet-httpsession-url-rewriting#servlet-url-rewriting )

This reproducer merely calls a servet and then a JSP, setting up a session in the URL. And indeed, the output truncates the ;jsessionid=xxx

17:29:14,076 INFO  [stdout] (http-localhost/127.0.0.1:8080-1) **** LoginServlet: request.getRequestURL() : http://localhost:8080/ServletSessionURLRewriting/LoginServlet
17:29:14,081 INFO  [stdout] (http-localhost/127.0.0.1:8080-1) **** LoginSuccess.jsp: request.getRequestURL() : http://localhost:8080/ServletSessionURLRewriting/LoginSuccess.jsp

although for the last line, my browser calls http://localhost:8080/ServletSessionURLRewriting/LoginSuccess.jsp;jsessionid=8tdi2T8okGxDb-KxPzWxj4D-
As such, if the method request.getPathInfo(); doesn't return the jsessionid, then the expected behaviour of UrlSessionTracking.java can't work as expected. Unfortunately I didn't manage to find any documentation about that on JBoss documentation, nor an alternative solution to parsing the URL to find the jsessionid.

Hope my explanations are clear enough,
Julien

**Comment by nbogojevic** [comment]
Thanks for the reproducer.

After double-checking, Tomcat 6,and JBoss 6 by extension, have no way to retrieve original URL. This makes impossible to use this kind of apporach to extract session id. We'd probably need to look into tomcat valves to do it. 

However, as starting from tomcat 7 and also in later versions of JBoss (undertow engine) we are able to retrieve original URI. So we’d probably go with recommendation – URL propagtion is supported only in tomcat 7+ and JBoss 7+/Wildfly 8+. That being said we still have issue as for tomcat 7 we'd need to use 
`getRequestURI` instead of `getPathInfo`.

**Comment by nbogojevic** [comment]
Fixed in v0.4.0 for Wildfly, jetty and tomcat 7+. 

No planned fix coming for jboss 6.x.
